---
sidebar: sidebar 
permalink: get-started/requirements.html 
keywords: kubernetes cluster, cluster requirements, version requirements, supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking 
summary: 立即開始驗證您環境的支援。 
---
= Astra Data Store預覽需求
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


開始驗證您的環境是否符合Astra Data Store預覽要求。

Astra Data Store預覽支援裸機和VM型部署。Astra Data Store預覽叢集可在具有四個以上工作節點的Kubernetes叢集上執行。Astra Data Store預覽軟體可與在相同Kubernetes叢集上執行的其他應用程式共存。

Astra Data Store預覽僅支援使用Astra Trident SCSI驅動程式、為Kubernetes工作負載配置持續磁碟區。Astra Data Store未來版本將支援VM工作負載。


NOTE: 如果您打算從Astra Control Center管理Astra Data Store預覽叢集、請確定您的Astra Data Store預覽叢集符合 https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html#kubernetes-cluster-general-requirements["將由Astra Control Center管理的叢集需求"^] 除了此處概述的要求之外、



== Kubernetes工作節點資源需求

以下是在Kubernetes叢集中的每個工作節點上、指派給Astra Data Store預覽軟體所需的資源：

|===
| 資源 | 最低 | 最大值 


| 資料磁碟機數量  a| 
* 3（存在獨立的快取裝置）
* 4（如果沒有快取裝置）

| 14 


| 資料磁碟機大小 | 100GiB | 4TiB 


| 選用快取裝置的數量 | 1（8GiB或更大） | 不適用 


| vCPU數量 | 10. | 10. 


| RAM | 35GiB | 35GiB 
|===

NOTE: 若要獲得最佳寫入效能、您應該設定專屬的高耐用度、低延遲、低容量快取裝置。

每個工作節點都有下列額外需求：

* 主機磁碟（開機）上的100GiB或更大可用空間、用於儲存Astra Data Store預覽記錄檔。
* 至少一個10GbE或更快的網路介面、適用於叢集、資料和管理流量。此外、也可以使用額外的1GbE或更快介面來分隔管理流量。




== 硬體與軟體需求

Astra Data Store預覽軟體已在下列硬體平台、軟體和儲存組態上通過驗證。請造訪 link:../support/get-help-ads.html["NetApp社群支援"] 如果Kubernetes叢集組態不同、

.硬體平台
* HPE 360
* HPE DL380
* Dell R640
* Dell R740


Astra Data Store預覽已通過下列磁碟機類型的驗證：

* *裸機部署*：Astra Data Store預覽安裝在Kubernetes叢集上、直接安裝在Linux叢集上、不需要任何Hypervisor
+
** SATA或NVMe TLC SSD


* *虛擬機器型部署*：Astra Data Store預覽安裝在ESXi叢集所裝載的Linux VM上的Kubernetes叢集上
+
** SATA、SAS或NVMe TLC SSD型資料存放區
** 以虛擬磁碟或通道磁碟機呈現的磁碟機





NOTE: 如果您的主機在硬體RAID控制器後方使用SSD、請將硬體RAID控制器設定為使用「PassthThrough」模式。


NOTE: 每個磁碟機都應該有唯一的序號。在虛擬機器建立虛擬機器期間、將屬性「dick.enableuid=true」新增至虛擬機器的進階設定。

.軟體
* Hypervisor：Astra Data Store預覽已通過VMware VM部署與ESXi 7.0的驗證。Astra Data Store預覽不支援KVM型部署。
* Astra Data Store預覽已在下列主機作業系統上通過驗證：
+
** Red Hat Enterprise Linux 8.4
** Red Hat Enterprise Linux 8.2
** Red Hat Enterprise Linux 7.9
** Red Hat Enterprise Linux CoreOS（RMCOS）
** CentOS 8.
** Ubuntu 20.04


* Astra Data Store預覽已通過下列Kubernetes發佈版本的驗證：
+
** Red Hat OpenShift 4.7
** Google Anthos 1.7
** Kubernetes 1.21
** Kubernetes 1.20





NOTE: Astra Data Store預覽需要Astra Trident版本210.1才能進行儲存資源配置和協調。請參閱 link:setup-ads.html#install-astra-trident["Astra Trident安裝說明"]。



== 網路需求

Astra Data Store預覽每個叢集需要一個IP位址才能用於MVIP。它必須是未使用或未設定的IP位址、與MIP位於同一子網路中。Astra Data Store預覽管理介面應與Kubernetes節點的管理介面相同。

此外、每個節點也可依照下表所述進行設定：


NOTE: 下表使用下列縮寫：MIP：管理IP位址CIP：叢集IP位址MVIP：管理虛擬IP位址

|===
| 組態 | 所需的IP位址 


| 每個節點一個網路介面  a| 
* 每個節點兩（2）個：
+
** MI/CIP：每個節點的管理介面上有一（1）個預先設定的IP位址
** 資料IP：每個節點的一（1）個未使用或未設定的IP位址、與MIP位於同一子網路中






| 每個節點有兩個網路介面  a| 
* 每個節點三個：
+
** MIP：每個節點的管理介面上有一（1）個預先設定的IP位址
** CIP：每個節點的資料介面上有一（1）個預先設定的IP位址、與MIP位於不同的子網路中
** 資料IP：在CIP所在的同一子網路中、每個節點有一（1）個未使用或未設定的IP位址




|===

NOTE: 對於這兩種組態、您應該省略叢集自訂資源（CR）檔案中的資料網路閘道欄位、即「astradscluster．yaml」。每個節點上現有的路由組態可容納所有位址。


NOTE: 這些組態不使用VLAN標記。



== Astra Trident

Astra Data Store預覽需要應用程式Kubernetes叢集執行Astra Trident 210.1。Astra Data Store預覽可設定為 link:../get-started/setup-ads.html#set-up-astra-data-store-as-storage-backend["儲存後端"] 使用Astra Trident來配置持續磁碟區。



== CNI組態

Astra Data Store預覽已通過下列CNI驗證：

* Calico和Weave Net CNI適用於香草Kubernetes叢集
* 適用於Red Hat OpenShift Container Platform（OCP）的OpenShift SDN
* Google Anthos的Cilium


這些CNI需要停用主機防火牆（firewalLD）。



== 持續磁碟區共用需求

每個Astra Data Store預覽叢集都支援使用持續磁碟區來滿足安裝在該叢集上的任何應用程式的儲存需求。Kubernetes應用程式會使用透過NFSv4.1共用的持續磁碟區來存取檔案、這需要AUTH_SYS驗證方法。



== 授權

Astra Data Store預覽需要Astra Data Store預覽授權才能提供完整功能。 https://www.netapp.com/cloud-services/astra/data-store-form/["請在此註冊"^] 取得Astra Data Store預覽授權。下載授權的指示將會在您註冊後寄送給您。



== 組態AutoSupport

Astra Data Store預覽需要AutoSupport 啟用功能才能連線AutoSupport 至該功能的後端。這可能是透過直接的網際網路存取或Proxy組態。

。 link:../get-started/install-ads.html#install-the-astra-data-store-cluster["用於傳送強制遙測AutoSupport 功能套件的定期設定"] 不應變更。如果您停用傳送週期AutoSupport 性的更新套件、叢集將會鎖定、而且在重新啟用週期性設定之前、無法建立新的磁碟區。



== 下一步

檢視 link:quick-start.html["快速入門"] 總覽：



== 以取得更多資訊

link:capabilities.html["Astra Data Store預覽限制"]
