---
sidebar: sidebar 
permalink: get-started/requirements.html 
keywords: kubernetes cluster, cluster requirements, version requirements, supported versions, apps, supported apps, mariadb, mysql, postgres, kubernetes version, ubuntu, image type, networking 
summary: 立即開始驗證您環境的支援。 
---
= Astra資料儲存區需求
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


開始驗證您的環境是否符合Astra Data Store要求。

Astra Data Store支援裸機和VM型部署。Astra Data Store叢集可在具有四個以上工作者節點的Kubernetes叢集上執行。Astra Data Store軟體可與在相同Kubernetes叢集上執行的其他應用程式共存。

* <<Kubernetes worker node resources>>
* <<Hardware and software>>
* <<Networking>>
* <<Astra Trident>>
* <<Container Network Interfaces>>
* <<Licensing>>



NOTE: 如果您打算從Astra Control Center管理Astra資料儲存區叢集、請確定您的Astra資料儲存區叢集符合 https://docs.netapp.com/us-en/astra-control-center/get-started/requirements.html#kubernetes-cluster-general-requirements["將由Astra Control Center管理的叢集需求"^] 除了此處概述的要求之外、



== Kubernetes工作節點資源

以下是在Kubernetes叢集中的每個工作節點上、指派給Astra Data Store軟體所需的資源：

|===
| 資源 | 最低 | 最大值 


| Astra Data Store叢集中的節點數 | 4. | 16 


| 資料磁碟機數量  a| 
* 3（存在獨立的快取裝置）
* 4（如果沒有快取裝置）

| 14 


| 資料磁碟機大小 | 100GiB | 4TiB 


| 選用快取裝置的數量 | 1（8GiB尺寸） | 不適用 
|===
Astra Data Store為每個Kubernetes工作節點支援下列vCPU和RAM組合：

* 9個vCPU、RAM為38GiB
* 23個vCPU、搭配94 GiB的RAM



NOTE: 若要獲得最佳寫入效能、您應該設定專屬的高耐用度、低延遲、低容量快取裝置。

每個工作節點都有下列額外需求：

* 用於儲存Astra Data Store記錄檔的主機磁碟（開機）可用空間為100GiB或更大。
* 至少一個10GbE或更快的網路介面、適用於叢集、資料和管理流量。此外、也可以使用額外的1GbE或更快介面來分隔管理流量。




== 硬體與軟體

Astra Data Store軟體已在下列硬體平台、軟體和儲存組態上通過驗證。請造訪 link:../support/get-help-ads.html["NetApp社群支援"] 如果Kubernetes叢集組態不同、



=== 硬體平台

* Dell R640
* Dell R740
* HPE 360
* HPE DL380
* Lenovo SR630
* Lenovo SR650



NOTE: VM型部署也可以使用列示為相容的伺服器 https://www.vmware.com/resources/compatibility/search.php["VMware相容性指南"^]。



=== 儲存設備

Astra Data Store已通過SATA、SAS及NVMe TLC SSD的驗證。

對於VM型部署、您可以使用呈現為虛擬磁碟或直通磁碟機的磁碟機。

[NOTE]
====
* 如果您的主機在硬體RAID控制器後方使用SSD、請將硬體RAID控制器設定為使用「PassthThrough」模式。
* 每個磁碟機都應該有唯一的序號。在虛擬機器建立虛擬機器期間、將屬性「dick.enableuid=true」新增至虛擬機器的進階設定。


====


=== 軟體

* Hypervisor：Astra Data Store已通過VMware VM部署與vSphere 7.0的驗證。Astra Data Store不支援KVM型部署。
* Astra Data Store已在下列主機作業系統上通過驗證：
+
** Red Hat Enterprise Linux 8.4
** Red Hat Enterprise Linux 8.2
** Red Hat Enterprise Linux 7.9
** Red Hat Enterprise Linux CoreOS（RMCOS）
** CentOS 8.
** Ubuntu 20.04


* Astra Data Store已通過下列Kubernetes發佈版本的驗證：
+
** Red Hat OpenShift 4.6到4.9
** Google Anthos 1.8到1.10
** Kubernetes 1.20到1.23
** Rancher RKE 1.3.3





NOTE: Astra Data Store需要Astra Trident來進行儲存資源配置和協調。支援Astra Trident版本210.1至22.04。請參閱 link:setup-ads.html#install-astra-trident["Astra Trident安裝說明"]。



== 網路

Astra Data Store每個叢集需要一個IP位址、才能用於MVIP。它必須是未使用或未設定的IP位址、與MIP位於同一子網路中。Astra Data Store管理介面應與Kubernetes節點的管理介面相同。

此外、每個節點也可依照下表所述進行設定：


NOTE: 下表使用下列縮寫：MIP：管理IP位址CIP：叢集IP位址MVIP：管理虛擬IP位址

|===
| 組態 | 所需的IP位址 


| 每個節點一個網路介面  a| 
* 每個節點兩（2）個：
+
** MI/CIP：每個節點的管理介面上有一（1）個預先設定的IP位址
** 資料IP：每個節點的一（1）個未使用或未設定的IP位址、與MIP位於同一子網路中






| 每個節點有兩個網路介面  a| 
* 每個節點三個：
+
** MIP：每個節點的管理介面上有一（1）個預先設定的IP位址
** CIP：每個節點的資料介面上有一（1）個預先設定的IP位址、與MIP位於不同的子網路中
** 資料IP：在CIP所在的同一子網路中、每個節點有一（1）個未使用或未設定的IP位址




|===

NOTE: 這些組態不使用VLAN標記。



== Astra Trident

Astra Data Store要求應用程式Kubernetes叢集執行Astra Trident以進行儲存資源配置和協調。支援Astra Trident版本210.1至22.04。Astra資料儲存區可設定為 link:../get-started/setup-ads.html#set-up-astra-data-store-as-storage-backend["儲存後端"] 使用Astra Trident來配置持續磁碟區。



== Container網路介面

Astra Data Store已通過下列Container Network Interfaces（Container Network Interfaces、簡稱CNI）的驗證。

* 適用於RKE叢集的Calico
* Calico和Weave Net CNI適用於香草Kubernetes叢集
* 適用於Red Hat OpenShift Container Platform（OCP）的OpenShift SDN
* Google Anthos的Cilium


[NOTE]
====
* 隨Cilium CNI部署的Astra Data Store需要Portmap外掛程式、才能支援hostPort。您可以將「CNI鏈結模式：portmap」新增至cilium組態地圖、然後重新啟動Cilium Pod、以啟用CNI鏈結模式。
* 只有Calico和OpenShift SDN CNI才支援啟用防火牆的組態。


====


== 授權

Astra Data Store需要有效授權才能啟用完整功能。

https://www.netapp.com/cloud-services/astra/data-store-form/["請在此註冊"^] 以取得Astra Data Store授權。下載授權的指示將會在您註冊後寄送給您。



== 下一步

檢視 link:quick-start.html["快速入門"] 總覽：



== 以取得更多資訊

link:capabilities.html["Astra資料儲存區的限制"]
